fix integration tests

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -22,9 +22,10 @@ jobs:
           cx_client_secret: 
           scan_types: sast
       - name: Check if failed authentication
-        if: ${{contains( steps.empty_client_secret.outcome, 'failure') == false}}
+        if: ${{contains( steps.empty_client_secret.outcome, 'success')}}
         run:  |
           echo "The authentication must fail if invalid client id or password is used"
+          echo "${{ steps.empty_client_secret.outcome}}"
       
       - name: Valid scenario 
         id: valid_scenario
@@ -39,8 +40,9 @@ jobs:
       - name: Check if completed
         if: ${{ contains( steps.valid_scenario.outcome, 'success') == false}}
         run: |
-          echo "The cli failed"
-          echo 1
+          echo "The action outcome should be success."
+          echo "${{ steps.valid_scenario.outcome}}"
+          exit 1
           
       - name: Test with preset name
         id: preset_name_test
@@ -52,9 +54,10 @@ jobs:
           cx_client_id: ${{ secrets.CX_CLIENT_ID }}
           cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
           scan_types: sast
-          additional_params: --sast-preset-name "Chekmarx Default Pedro" --sast-incremental false
+          additional_params: --sast-preset-name "Chekmarx Default Fake" --sast-incremental false
       - name: Check if preset name completed
-        if: ${{contains( steps.empty_client_secret.outcome, 'failure') == false}}
+        if: ${{contains( steps.preset_name_test.outcome, 'success')}}
         run: |
-          echo "The cli failed"
+          echo "The cli should fail. Wrong preset name provided"
+          echo "${{ steps.preset_name_test.outcome}}"
           exit 1
