test in multiple os

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -4,11 +4,16 @@ on: push
 
 jobs:
   test:
-    runs-on: ubuntu-latest
-    name: Test if action is working 
+    strategy:
+      matrix:
+        os: [ubuntu-latest, windows-latest, macOS-latest]
+    runs-on: ${{ matrix.os }}
+
+    name: Unit Testing
     steps:
       - name: Checkout the repository
         uses: actions/checkout@v1
+      
       - name: Run with empty client and secret
         id: empty_client_secret
         uses: ./
@@ -18,13 +23,12 @@ jobs:
           cx_client_id: ''
           cx_client_secret: ''
           scan_types: sast
-      - name: Get the output
-        run: echo "${{ steps.empty_client_secret.outputs.cxcli }}"
       - name: Check if failed authentication
-        if: ${{ contains( steps.empty_client_secret.outputs.cxcli, 'Failed to authenticate')}}
+        if: ${{contains( steps.empty_client_secret.outputs.cxcli, 'Failed to authenticate') == false}}
         run:  |
           echo "The authentication must fail if invalid client id or password is used"
           exit 1
+      
       - name: Valid scenario 
         id: valid_scenario
         uses: ./
@@ -34,6 +38,8 @@ jobs:
           cx_client_id: ${{ secrets.CX_CLIENT_ID }}
           cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
           scan_types: sast
-      - name: Check if failed authentication
-        if: ${{ contains( steps.valid_scenario.outputs.cxcli, 'Completed')}}
-        run: echo "The cli failed"
+      - name: Check output contains completed
+        if: ${{ contains( steps.valid_scenario.outputs.cxcli, 'Completed') == false}}
+        run: |
+          echo "The cli failed"
+          exit 1
