add exit code

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -22,7 +22,9 @@ jobs:
         run: echo "${{ steps.empty_client_secret.outputs.cxcli }}"
       - name: Check if failed authentication
         if: ${{ contains( steps.empty_client_secret.outputs.cxcli, 'Failed to authenticate')}}
-        run: echo "The authentication must fail if invalid client id or password is used"
+        run:  |
+          echo "The authentication must fail if invalid client id or password is used"
+          exit 1
       - name: Valid scenario 
         id: valid_scenario
         uses: ./
